AgenciaServitec/practice-system

- packages/hosting/src/pages/home/index.js
- packages/hosting/src/router/index.js
> Add home page

- packages/hosting/src/pages/administration/practices/sheets/PracticesSheet5.jsx
- packages/hosting/src/pages/administration/practices/sheets/index.js
> Add sheet 5

- packages/hosting/src/pages/administration/practices/sheets/PracticesSheet7.jsx
- packages/hosting/src/pages/administration/practices/sheets/index.js
> add sheet 7

- packages/hosting/src/pages/administration/practices/sheets/PracticesSheet7.jsx
- packages/hosting/src/pages/administration/practices/sheets/PracticesSheet8.jsx
- packages/hosting/src/pages/administration/practices/sheets/index.js
> add sheet 8 and refactored sheet 7

- packages/hosting/src/pages/administration/practices/sheets/PracticesSheet6.jsx
- packages/hosting/src/pages/administration/practices/sheets/index.js
> add contente practices sheet 6

- packages/hosting/src/pages/administration/practices/sheets/PracticesSheet4.jsx
- packages/hosting/src/pages/administration/practices/sheets/PracticesSheet5.jsx
- packages/hosting/src/pages/administration/practices/sheets/PracticesSheet9.jsx
- packages/hosting/src/pages/administration/practices/sheets/index.js
> Add practices sheet 9

- packages/hosting/src/components/layout/DrawerLayout.js
- packages/hosting/src/pages/administration/companies/CompanyTable.js
- packages/hosting/src/pages/administration/companies/_companyId/index.jsx
> refactored companies

- packages/hosting/src/pages/home/index.js
> Add shortcuts to modules

- packages/hosting/src/pages/administration/practices/_practiceId/module1/sheets/PracticesSheet3.jsx
- packages/hosting/src/pages/administration/practices/_practiceId/module1/sheets/index.js
> add missing fields in sheet 3 and update css "row-list"

- packages/hosting/src/pages/administration/practices/_practiceId/module1/sheets/PracticesSheet1.jsx
- packages/hosting/src/pages/home/index.js
> add missing field and update home page

- packages/hosting/src/pages/administration/practices/_practiceId/module1/annexs/annex4/Sheet1.jsx
- packages/hosting/src/pages/administration/practices/_practiceId/module1/annexs/annex4/index.jsx
- packages/hosting/src/pages/administration/practices/_practiceId/module1/sheets/PracticesSheet5.jsx
- packages/hosting/src/pages/administration/practices/_practiceId/module1/sheets/index.js
> add-dinamic-data-annex4-

- packages/hosting/src/pages/administration/practices/_practiceId/module1/annexs/annex2/Sheet1.jsx
- packages/hosting/src/pages/administration/practices/_practiceId/module1/annexs/annex4/Sheet1.jsx
- packages/hosting/src/pages/administration/practices/_practiceId/module1/annexs/annex4/index.jsx
> Add annex4 information

- packages/hosting/src/pages/administration/practices/_practiceId/module1/annexs/annex4/Sheet1.jsx
- packages/hosting/src/pages/administration/practices/_practiceId/module1/annexs/annex6/Sheet1.jsx
> Refactor annex6

- packages/hosting/src/pages/administration/users/_userId/index.jsx
> add api in register practitioner

- packages/hosting/src/pages/practices/_practiceId/module1/annexs/annex3/Sheet1.jsx
- packages/hosting/src/pages/practices/_practiceId/module1/annexs/annex3/index.jsx
> add validation

- packages/hosting/src/pages/practices/_practiceId/module1/annexs/annex2/Sheet1.jsx
- packages/hosting/src/pages/practices/_practiceId/module1/annexs/annex3/Sheet1.jsx
- packages/hosting/src/pages/practices/_practiceId/module1/annexs/annex4/InstructionsEvaluation.js
- packages/hosting/src/pages/practices/_practiceId/module1/annexs/annex4/Sheet1.jsx
- packages/hosting/src/pages/practices/_practiceId/module1/sheets/PracticesSheet7.jsx
> add table for indicators evaluation

- packages/hosting/src/pages/practices/_practiceId/InformationModal.jsx
- packages/hosting/src/pages/practices/_practiceId/module1/annexs/annex4/Sheet1.jsx
> New refactor

- packages/hosting/src/pages/practices/_practiceId/ManageCreatePractice.js
- packages/hosting/src/pages/practices/_practiceId/index.jsx
- packages/hosting/src/pages/practices/_practiceId/module1/annexs/annex4/Sheet1.jsx
- packages/hosting/src/pages/practices/_practiceId/module1/annexs/annex4/index.jsx
> view practices for representativeCompany

- packages/hosting/src/pages/administration/companies/_companyId/index.jsx
- packages/hosting/src/pages/practices/_practiceId/module1/sheets/PracticesSheet2.jsx
- packages/hosting/src/pages/register/index.jsx
add upload for isotype and logotype
> add refactor register page for coordinator

- packages/hosting/src/data-list/acls.json
- packages/hosting/src/pages/practices/_practiceId/ObservationOfAnnex.jsx
- packages/hosting/src/pages/practices/_practiceId/module1/ObservationsList.jsx
- packages/hosting/src/pages/practices/_practiceId/module1/annexs/annex2/Sheet1.jsx
- packages/hosting/src/pages/practices/_practiceId/module1/annexs/annex3/Sheet1.jsx
**Vista Supervisor**
**Vista usuario**
> improved observations

- packages/hosting/src/pages/practices/_practiceId/module1/annexs/annex4/Sheet1.jsx
> Add 0.5 to radiogroup

- packages/hosting/src/components/ui/showStaticMap.js
- packages/hosting/src/config/configs.json
- packages/hosting/src/config/index.js
- packages/hosting/src/pages/practices/_practiceId/module1/sheets/PracticesSheet11.jsx
- packages/hosting/src/pages/practices/_practiceId/module1/sheets/index.js
> add component map static

- packages/hosting/src/pages/practices/_practiceId/module/annexs/annex2/Sheet1.jsx
**Vista usuario**
**Vista supervisor y representante de empresa**
> disabled input when roleCode is different to user

- packages/hosting/src/data-list/professionalCareer.json
- packages/hosting/src/pages/practices/_practiceId/InitialInformation.jsx
> Refactor professionalCareer.json

- packages/hosting/src/components/layout/HeaderLayout.js
> use hook useDevice

- packages/hosting/src/pages/practices/_practiceId/index.jsx
- packages/hosting/src/pages/practices/_practiceId/module/annexs/annex6/Sheet1.jsx
- packages/hosting/src/pages/practices/_practiceId/module/annexs/annex6/index.jsx
> Add a informative component to annex6

- packages/hosting/src/pages/practices/_practiceId/module/annexs/AnnexButtons.js
- packages/hosting/src/pages/practices/_practiceId/module/annexs/annex2/index.jsx
- packages/hosting/src/pages/practices/_practiceId/module/annexs/annex3/index.jsx
- packages/hosting/src/pages/practices/_practiceId/module/annexs/annex4/index.jsx
- packages/hosting/src/pages/practices/_practiceId/module/annexs/annex6/index.jsx
> remove refused buttons

- packages/hosting/src/providers/GlobalDataProvider.js
> Validar los usuarios a traer según el roleCode

- packages/hosting/src/pages/register/RegisterAcademicCoordinator.jsx
> Añadí el campo de carrera profesional para coordinación académica

- firestore.indexes.json
- packages/hosting/src/pages/administration/users/Users.Table.jsx
- packages/hosting/src/pages/practices/_practiceId/ManageCreatePractice.js
- packages/hosting/src/providers/GlobalDataProvider.js
> Traer usuarios según la carrera profesional

- packages/hosting/src/components/ui/AddButton.js
- packages/hosting/src/pages/practices/_practiceId/ManageCreatePractice.js
- packages/hosting/src/pages/practices/_practiceId/index.jsx
- packages/hosting/src/pages/practices/index.js
> Validate creation of practices

- packages/hosting/src/pages/home/index.js
- packages/hosting/src/pages/practices/_practiceId/InformationModal.jsx
> Refix role representative company
